# Sample .travis.yml for R projects.
#
# See the r-travis repo and its wiki
#   https://github.com/craigcitro/r-travis/wiki
#   https://github.com/eddelbuettel/r-travis/

language: c

os:
  - linux
  - osx

osx_image: xcode7.1

sudo: required

dist: trusty

env:
  global:
    - secure: b9DfgCLxLdBReSvku0eSExzvip4/gTVjmtEKaV8lsOOZPK4oCrZQU0IYWezAVGOum8i2dW1wqXcEGULPsRGHl3Vci4YI+z5B6W93qVo4GVghxmkO+2nLgb/tS2QvCThBF1XDuhmwvD1lvAEJyEzxVwpt81jM58qQuLDDAL3bMOII0uCWBebGdtVKhev2UuIWzE5kArrAmzp9eHAlcM5Raft3rrOl7wLW9s1zPlfKUKVU5UOOOw+5V7Ordwjc+jCObxfXrLIwq6f1acH8bZlJ22K2MpI8TpogKvSpnNGKWQ8KZXaGnJFtzTJUfePvPinVCWj+qKIWytilqcEYE648hykCe6xFhfqsQemjcdTEEPFdynrNLB1wx2f0fW6lHPjiODYGAmtoDm6TQlkkltHJdLzpjupR9E9T0QVgcL9hGZA2Z3OvlXGeGo+dBkE0b+9aYnwVMxepvbK1z3nHL9VNiO4llKG9Cr4x4H7GcEd47QDezd/6jfSZUttvMfAhxEoXkkzcgSaTZGRPnFIEZbcixs8+oUkTqGbh6UyUKKUXZaRDE84nS9y2G2iSFWk4yd9oppjyjdysrgSMCoKiNEnQSu3c8/5KHOhglH1UsQgfT62Me7wOLSumvM9ptHeo39SBI8o3zs0vBq1VUTqDie7GsmCnliiZvb2xaqJUy8fbBno=
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-vignettes --no-manual"
    - OS=$(uname -s)
  matrix:
    - _R_CHECK_CRAN_INCOMING_=FALSE
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran" RUN_RE2R_BENCHMARK="TRUE" PANDOC_VERSION="1.15.2" BOOTSTRAP_PANDOC="1"

before_install:
  - echo "options(repos = c(CRAN='http://cran.r-project.org'))" >> ~/.Rprofile
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r_binary Rcpp RCurl stringi ggplot2 dplyr curl jsonlite yaml tidyr RcppParallel markdown
  - ./travis-tool.sh install_r plotly covr
  - ./travis-tool.sh install_deps

before_script:
  - ./travis-tool.sh dump_sysinfo

script:
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - ./travis-tool.sh dump_logs
  - Rscript -e 'if ( Sys.getenv("OS") == "Linux" && Sys.getenv("RUN_RE2R_BENCHMARK") == "TRUE") {library(devtools); install(); build_vignettes();}' 
  - cd ./inst/doc/
  - touch .nojekyll
  - cp re2r-intro.html index.html
  - git init
  - git checkout -b gh-pages
  - git add --all
  - git -c user.name='travis' -c user.email='travis@travis.travis' commit -m "update re2r gh-pages"
  - if [ "${RUN_RE2R_BENCHMARK}" = "TRUE" ] && [ "${OS}" = "Linux" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then git push --force --quiet "https://qinwf:$GITHUB_API_KEY@github.com/qinwf/re2r_doc.git" gh-pages > /dev/null 2>&1 ; Rscript -e 'library("covr");codecov()'; fi;

notifications:
  email:
    on_success: change
    on_failure: always
